logging:
  level: INFO
  loggers:
    com.example: DEBUG

server:
  applicationConnectors:
    - type: http
      port: 8090
  adminConnectors:
    - type: http
      port: 8091

defaultName: Aaron
template: Hello, %s!